[build-system]
requires = ["maturin>=1.1,<2.0"]
build-backend = "maturin"

[project]
name = "rare-helixerpost"
version = "0.1.0" # Don't forget to match with Cargo.toml and docs/source/conf.py
authors = [
]
description = "Sliding window assessment to determine regions of the genome which are likely gene containing"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
dependencies = [
]

[project.urls]
"Homepage" = "https://github.com/anthony-aylward/HelixerPost"
"Documentation" = "https://anthony-aylward.github.io/HelixerPost"

[project.scripts]
helixer_post_bin = "rare_helixerpost.rare_helixerpost:main"

[tool.maturin]
module-name = "rare_helixerpost.helixer_post_bin"
include = ["LICENSE"]

